apiVersion: v1
kind: Service
metadata:
  name: scalyshop-frontend
  namespace: scalyshop-manifest
spec:
  selector:
    app: scalyshop-frontend
  ports:
    - port: 80         # The front end exposes HTTP port 80
      targetPort: 5173 # Mapped to front-end container internal port 5046
      protocol: TCP
  type: NodePort
